parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appEnv: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataFixtures/'

    App\Service\PdfService:
        arguments:
            $gotenbergUrl: '%env(GOTENBERG_URL)%'

    App\Service\ImageUploader:
        arguments:
            $uploadDirectory: '%upload_directory%'

    App\Controller\ImageController:
        arguments:
            $uploadDirectory: '%upload_directory%'
        tags: ['controller.service_arguments']

when@dev:
    services:
        App\DataFixtures\AppFixtures:
            autowire: true
            autoconfigure: true
            arguments:
                $uploadDirectory: '%upload_directory%'
